spring:
  application:
    name: zerobase-dividend

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  fcm:
    certification: tossme-22f19-firebase-adminsdk-rcm2y-472b4affb6.json
